version: '3'
services:
  api:
    image: eoffers/api:latest
    ports:
      - "5000:443"
    volumes:
      - "~/config/config.net.eoffers.api.php:/var/config/config.net.eoffers.api.php"
      - "~/net.eoffers.api:/var/www/html"
    command: "sh etc/symfonize_dev.sh"