<?php

namespace AppBundle\Repository;

/**
 * BranchPreferencesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BranchPreferencesRepository extends \Doctrine\ORM\EntityRepository
{
    public function getPreferencesByIdOrBranchSlug($id)
    {
        $qb = $this->createQueryBuilder('bp');

        return $qb->join('bp.branch', 'branch')
            ->where('bp.id = :id')
            ->orWhere('branch.slug = :id')
            ->setParameter('id', $id)
            ->getQuery()
            ->getOneOrNullResult();
    }
}
