<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * BranchProfileRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BranchProfileRepository extends EntityRepository
{
    public function getProfileByBranchSlug($slug)
    {
        return $this->createQueryBuilder('profile')
            ->join('profile.branch', 'branch')
            ->where('branch.slug = :slug')
            ->setParameter('slug', $slug)
            ->getQuery()
            ->getOneOrNullResult();
    }

    /**
     * @param $industryId
     * @param $searchText
     * @param $rating
     * @return mixed
     */
    public function getProfiles($industryId, $searchText, $rating)
    {
        $qb = $this->createQueryBuilder('profile');
        
        $qb->leftJoin('profile.addresses', 'addresses')
            ->join('profile.branch', 'branch')
            ->join('branch.company', 'company');
        
        if($industryId) {
            $qb->andWhere('company.industry = :industryId')
                ->setParameter('industryId', $industryId);
        }
        
        if($searchText) {
	        $qb->andWhere($qb->expr()->like('profile.name', ':searchText'))
    	        ->setParameter('searchText', '%' . $searchText . '%');
        }
        
        if($rating) {
            $qb->andWhere($qb->expr()->gte('profile.average_rating*5', ':rating'))
                ->setParameter('rating', $rating);
        }

        return $qb->getQuery()
            ->getResult();
    }
}