<?php

namespace AppBundle\Repository;

/**
 * DrchronoPracticeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DrchronoPracticeRepository extends \Doctrine\ORM\EntityRepository
{
}
