<?php

namespace AppBundle\Repository;

/**
 * DrchronoDoctorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DrchronoDoctorRepository extends \Doctrine\ORM\EntityRepository
{
}
