<?php

namespace AppBundle\Repository;

/**
 * EncompassLoanOfficerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EncompassLoanOfficerRepository extends \Doctrine\ORM\EntityRepository
{
}
