<?php

namespace AppBundle\Repository;

/**
 * EncompassTokenRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EncompassTokenRepository extends \Doctrine\ORM\EntityRepository
{
}
