<?php

namespace AppBundle\Repository;

/**
 * PracticePantherTokenRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PracticePantherTokenRepository extends \Doctrine\ORM\EntityRepository
{
}
