<?php

namespace AppBundle\Repository;

use AppBundle\Entity\User;
use Doctrine\ORM\EntityRepository;

/**
 * ReferralRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReferralRepository extends EntityRepository
{
    public function filter(User $user, $active)
    {
        $qb = $this->createQueryBuilder('r')
            ->join('r.user', 'user')
            ->where('user = :user')
            ->setParameter('user', $user);

        switch ($active) {
            case ('active'):
                $qb->andWhere('r.active = true');
                break;
            case ('inactive'):
                $qb->andWhere('r.active = false');
                break;
        }

        return $qb->getQuery();
    }

    public function getCount(User $user = null)
    {
        $qb =  $this->createQueryBuilder('r');

        if (null !== $user) {
            $qb->join('r.user', 'user')
                ->where('user = :user')
                ->setParameter('user', $user);
        }

        return $qb->select('count(r.id)')
            ->getQuery()
            ->getSingleScalarResult();
    }
}
