<?php

namespace AppBundle\Repository;

/**
 * SurveyPushUrlRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SurveyPushUrlRepository extends \Doctrine\ORM\EntityRepository
{
}
